dist: bionic
language: cpp

jobs:
  include:
  - os: linux
    compiler: gcc
    dist: bionic
    before_install:
      - .travis/preinstall.sh
    script:
      - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make -j $(getconf _NPROCESSORS_ONLN) && ctest
  - os: linux
    compiler: clang
    dist: bionic
    before_install:
      - .travis/preinstall.sh
    script:
      - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake .. && make -j $(getconf _NPROCESSORS_ONLN) && ctest