dist: bionic
language: cpp
os: linux
before_install:
  - .travis/preinstall.sh
compiler:
  - gcc
  - clang
env:
  - DEBUG=-DCMAKE_BUILD_TYPE=DEBUG 
  - DEBUG=-DCMAKE_BUILD_TYPE=DEBUG USE_ROCKSDB=-DBUILD_ROCKSDB_STORAGE=TRUE
  - RELEASE=-DCMAKE_BUILD_TYPE=RELEASE
  - RELEASE=-DCMAKE_BUILD_TYPE=RELEASE USE_ROCKSDB=-DBUILD_ROCKSDB_STORAGE=TRUE
script:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake $DEBUG $RELEASE $USE_ROCKSDB .. && make -j $(getconf _NPROCESSORS_ONLN) && ctest

